<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Irudiak\Irudia1.png" />
    <None Remove="Irudiak\Irudia2.png" />
    <None Remove="Irudiak\Irudia3.png" />
    <None Remove="Irudiak\Irudia4.png" />
    <None Remove="Irudiak\Irudia5.png" />
    <None Remove="Irudiak\Irudia6.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Irudiak\Irudia1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Irudiak\Irudia2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Irudiak\Irudia3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Irudiak\Irudia4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Irudiak\Irudia5.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Irudiak\Irudia6.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

	<ItemGroup>
		<None Include="Irudiak\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
